export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER-FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const ADD_CHILDREN ='ADD_CHILDREN';
export const ADD_ABOUT ='ADD_ABOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';
export const REPORT_FAIL = 'REPORT_FAIL';
export const ALL_PROFILE_FAIL ='ALL_PROFILE_FAIL';
export const ALL_PROFILE_SUCCESS ='ALL_PROFILE_SUCCESS';
export const ALL_REPORT_SUCCESS =  'ALL_REPORT_SUCCESS';
export const ALL_REPORT_FAIL = 'ALL_REPORT_FAIL';
export const CLEAR_REPORT = 'CLEAR_REPORT';
export const VIEW_REPORT_SUCCESS = 'VIEW_REPORT_SUCCESS';
export const VIEW_REPORT_FAIL = 'VIEW_REPORT_FAIL';








